#!/bin/bash
# Update sbuild chroots
set -e

PROGRAM_NAME="$(basename "$0")"

. $(dirname "$0")/common.sh
general_init "$@"

for distribution in $DISTRIBUTIONS_TO_PACKAGE; do
	for arch in $ARCHES_TO_PACKAGE; do
		DISTRIBUTIONS="$distribution" ARCHES="$arch" . $(dirname "$0")/setup.sh --update
	done
done
